# Simplified AQI Prediction System Configuration

# Data source configuration
data:
  location:
    latitude: 31.5204
    longitude: 74.3587
    name: "Lahore, Pakistan"
    timezone: "Asia/Karachi"

  # Open-Meteo API settings
  api:
    base_url: "https://air-quality-api.open-meteo.com/v1/air-quality"
    weather_url: "https://api.open-meteo.com/v1/forecast"
    timeout: 30
    retries: 3

  # Historical data parameters
  historical:
    start_date: "2023-01-01" # Start from 2023 for faster processing
    end_date: null # null means today
    variables:
      - "pm10"
      - "pm2_5"
      - "carbon_monoxide"
      - "nitrogen_dioxide"
      - "sulphur_dioxide"
      - "ozone"
      - "aerosol_optical_depth"
      - "dust"
      - "uv_index"

    weather_variables:
      - "temperature_2m"
      - "relative_humidity_2m"
      - "pressure_msl"
      - "cloud_cover"
      - "wind_speed_10m"
      - "wind_direction_10m"
      - "precipitation"

  # Data processing
  processing:
    missing_value_threshold: 0.1
    interpolation_method: "linear"
    resample_frequency: "1H"

# Feature engineering configuration
features:
  # Time-based features
  time_features:
    enable: true
    features:
      - "hour"
      - "day_of_week"
      - "month"
      - "is_weekend"

  # Lag features
  lag_features:
    enable: true
    lag_hours: [1, 3, 6, 12, 24]
    variables: ["pm2_5", "pm10", "temperature_2m", "wind_speed_10m"]

  # Rolling window features
  rolling_features:
    enable: true
    windows: [3, 6, 12]
    statistics: ["mean", "std"]
    variables: ["pm2_5", "pm10", "temperature_2m"]

  # Feature selection
  selection:
    enable: true
    max_features: 30

# Model training configuration
models:
  target: "pm2_5"

  # Train-test split
  train_test_split:
    test_size: 0.2
    random_state: 42

  # Scikit-learn models
  sklearn:
    enable: true
    models:
      random_forest:
        enable: true
        params:
          n_estimators: 100
          max_depth: 15
          random_state: 42

      xgboost:
        enable: true
        params:
          n_estimators: 100
          learning_rate: 0.1
          max_depth: 6
          random_state: 42

      linear_regression:
        enable: true
        params:
          fit_intercept: true

    # Ensemble configuration
    ensemble:
      enable: true
      method: "voting"

  # Deep learning models
  deep_learning:
    enable: true

    # LSTM model
    lstm:
      enable: true
      architecture:
        sequence_length: 24
        lstm_units: [64, 32]
        dropout: 0.2
        dense_units: [32, 16]

      training:
        epochs: 50
        batch_size: 32
        validation_split: 0.2
        early_stopping:
          enable: true
          patience: 10

# Hopsworks configuration (optional - can be disabled)
hopsworks:
  enable: true # Set to true when you have API keys
  project_name: "pearls_aqi_prediction"

  feature_store:
    feature_group_name: "aqi_features"
    feature_group_version: 1

  model_registry:
    sklearn_model_name: "aqi_sklearn_ensemble"
    dl_model_name: "aqi_deep_learning"

# Streamlit app configuration
webapp:
  title: "AQI Prediction Dashboard"
  page_title: "AQI Predictor"
  page_icon: "🌬️"
  layout: "wide"

  # Refresh intervals (in seconds)
  refresh_intervals:
    real_time_data: 300
    forecasts: 3600

  # Chart configurations
  charts:
    height: 400

  # SHAP explanations
  explainability:
    enable: true
    max_features_display: 10

# Basic logging configuration
logging:
  level: "INFO"
  console:
    enable: true
