name: Manual Model Training (Incremental)

on:
  # schedule:
  #   # Run daily at 2 AM UTC (DISABLED - using hourly full pipeline instead)
  #   - cron: "0 2 * * *"
  workflow_dispatch: # Manual triggering only

jobs:
  train-models:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r aqi_predictor/requirements.txt

      - name: Set up environment variables
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
          HOPSWORKS_HOST: ${{ secrets.HOPSWORKS_HOST }}
        run: |
          echo "HOPSWORKS_API_KEY=$HOPSWORKS_API_KEY" >> .env
          echo "HOPSWORKS_PROJECT_NAME=$HOPSWORKS_PROJECT_NAME" >> .env
          echo "HOPSWORKS_HOST=$HOPSWORKS_HOST" >> .env

      - name: Run daily model training
        run: |
          cd aqi_predictor
          python run_complete_pipeline.py incremental

      - name: Upload model artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: trained-models
          path: |
            aqi_predictor/models/
          retention-days: 30

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: daily-training-logs
          path: |
            aqi_predictor/*.log
            aqi_predictor/models/
          retention-days: 7
