name: Hourly Full Pipeline Training

on:
  schedule:
    # Run every hour at minute 0
    - cron: "0 * * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r aqi_predictor/requirements.txt

      - name: Set up environment variables
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
          HOPSWORKS_HOST: ${{ secrets.HOPSWORKS_HOST }}
        run: |
          cd aqi_predictor
          echo "HOPSWORKS_API_KEY=$HOPSWORKS_API_KEY" >> .env
          echo "HOPSWORKS_PROJECT_NAME=$HOPSWORKS_PROJECT_NAME" >> .env
          echo "HOPSWORKS_HOST=$HOPSWORKS_HOST" >> .env

      - name: Run full pipeline training
        run: |
          cd aqi_predictor
          python run_complete_pipeline.py full

      - name: Upload model artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: hourly-trained-models
          path: |
            aqi_predictor/models/
          retention-days: 7

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: full-pipeline-logs
          path: |
            aqi_predictor/*.log
            aqi_predictor/models/
            aqi_predictor/data/
          retention-days: 7
