name: "AQI Model Training"

on:
  schedule:
    - cron: "0 6 * * *" # Run daily at 6 AM UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          cd aqi_predictor
          pip install pandas numpy scikit-learn xgboost tensorflow requests pyyaml streamlit plotly joblib hopsworks

      - name: Run AQI pipeline with Hopsworks (no local files)
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT: ${{ secrets.HOPSWORKS_PROJECT }}
        run: |
          cd aqi_predictor
          python pipelines/pipeline.py --mode full --years 1 --features 25

      - name: Verify Hopsworks integration
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT: ${{ secrets.HOPSWORKS_PROJECT }}
        run: |
          cd aqi_predictor
          echo "✅ Pipeline completed - all data and models stored in Hopsworks cloud"
          echo "🔍 No local files created - using cloud storage only"
